apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "accounts-api.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/accounts/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/accounts/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/accounts/db/pass
    secretKey: DB_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/accounts/cio/api_key
    secretKey: CUSTOMER_IO_API_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/users/email/user
    secretKey: EMAIL_USERNAME
  - remoteRef:
      key: {{ .Release.Namespace }}/users/email/password
    secretKey: EMAIL_PASSWORD
  - remoteRef:
      key: {{ .Release.Namespace }}/users/email/host
    secretKey: EMAIL_HOST
  {{- if eq .Release.Namespace "dev" }}
  - remoteRef:
      key: {{ .Release.Namespace }}/accounts/mixpanel/project_token
    secretKey: MIXPANEL_PROJECT_TOKEN
  {{- end }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "accounts-api.fullname" . }}-secret
    template:
      metadata: {}
